### ISSUE TITLE
获取维权订单时遇到问题

### ISSUE THREAD

**Issue by hainuo** [ennnnny/tbk#9]
```
$return = $app->order->getRefund(['search_option'=>json_encode($param)]);
```
使用这种方式 报错信息为 
```
{"code":40,"msg":"Missing required arguments:search_option.biz_type","request_id":"10eoe5pe8w1z3"}
```
使用下面的方式
```
$return = $app->order->getRefund(['search_option'=>$param]);
```
sdk会报错
```
[2019-12-07T12:24:21+08:00][ error ] substr() expects parameter 1 to be string, array given
error
[2019-12-07T12:24:21+08:00][ error ] #0 [internal function]: think\Error::appError(2, 'substr() expect...', '/Users/hainuo/s...', 139, Array)
#1 /Users/hainuo/vendor/ennnnny/tbk/src/Kernel/BaseClient.php(139): substr(Array, 0, 1)
#2 /Users/hainuo/vendor/ennnnny/tbk/src/Kernel/BaseClient.php(97): ETaobao\Kernel\BaseClient->curl('https://eco.tao...', Array)
#3 /Users/hainuo/vendor/ennnnny/tbk/src/Tbk/Order/Client.php(44): ETaobao\Kernel\BaseClient->httpPost('taobao.tbk.rela...', Array)
#4 /Users/hainuo/application/api/job/GetTbkOrder.php(489): ETaobao\Tbk\Order\Client->getRefund(Array)
```

感觉在判断的时候没有处理好对多维数组的处理 

php执行方式为 命令行模式下执行
php版本号为
```
PHP 7.3.11 (cli) (built: Oct 24 2019 11:29:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by ennnnny** [comment]
对于多维数组的话，需要对其进行json_encode处理。你第一种方式是对的，报错信息应该是漏了这个biz_type参数。我已在新版本中更新了对参数中存在多维数组的处理了。
